name: Capture Calendar (mobile shot)

on:
  workflow_dispatch:  # ← 수동 실행 버튼

permissions:
  contents: write     # ← 이미지 커밋하려면 필요

jobs:
  capture:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install Korean fonts
        run: |
          sudo apt-get update
          sudo apt-get install -y fonts-noto-cjk fonts-noto-color-emoji

      - name: Install deps (puppeteer)
        run: |
          npm ci || npm i

      - name: Run node capture.js
        run: node capture.js

      - name: Commit & push image
        run: |
          mkdir -p docs/capture
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add docs/capture/calendar_mobile.png
          git commit -m "chore: update mobile calendar screenshot $(date -u +'%Y-%m-%dT%H:%M:%SZ')" || echo "no changes"
          git push
