name: Capture Calendar (mobile shot)

on:
  workflow_dispatch: {}
  schedule:
    - cron: "0 */3 * * *"   # 3시간마다

permissions:
  contents: write   # 커밋/푸시 권한

jobs:
  capture:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Install deps (Puppeteer + fonts)
        run: |
          npm i --no-audit --no-fund puppeteer@22.15.0
          sudo apt-get update
          sudo apt-get install -y fonts-noto-cjk fonts-noto-color-emoji

      - name: Capture mobile screenshot
        env:
          TARGET_URL: "https://sung5727.github.io/WEB_celrender/"
          OUT_PATH: "public/calendar_mobile.png"   # ← URL 말고 '리포 경로'
          CAL_SELECTOR: "#calendarCapture"
          CROP_RATIO: "0.88"
        run: node capture.js    # ← 루트의 capture.js 실행

      - name: Commit & push image
        run: |
          git config user.name  "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add public/calendar_mobile.png
          git commit -m "Update calendar_mobile.png [skip ci]" || echo "No changes"
          git push
