name: Capture Calendar (mobile shot)

on:
  workflow_dispatch:
  # 매일 UTC 13:05 = KST 22:05
  schedule:
    - cron: "5 13 * * *"

permissions:
  contents: write   # push 권한

concurrency:
  group: capture-calendar
  cancel-in-progress: true

jobs:
  capture:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0    # rebase/push에 필요

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install puppeteer (local)
        run: npm install puppeteer

      - name: Run capture.js
        run: node capture.js

      - name: Verify output
        run: |
          echo "== 파일 확인 =="
          mkdir -p docs/capture
          ls -al docs/capture || true
          echo "== 해시 =="
          sha256sum docs/capture/calendar_mobile.png || true

      - name: Commit & push image (rebase-safe)
        shell: bash
        run: |
          set -e

          # 깔끔한 작업 트리 보장
          git fetch origin main
          git checkout -B main origin/main

          # 사용자 설정
          git config user.name  "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

          # 변경분만 스테이징
          git add docs/capture/calendar_mobile.png

          # 변경 없으면 종료
          if git diff --cached --quiet; then
            echo "No diff for calendar_mobile.png — nothing to commit."
            exit 0
          fi

          # 커밋
          git commit -m "chore: update mobile calendar screenshot $(date -u +'%Y-%m-%dT%H:%M:%SZ')"

          # rebase-safe 푸시 (경쟁 상황 대비 3회 재시도)
          for i in 1 2 3; do
            git pull --rebase origin main || true
            if git push origin HEAD:main; then
              echo "Push succeeded."
              exit 0
            fi
            echo "Push failed, retrying ($i/3)..."
            sleep 2
          done

          # 마지막 방어선
          git push --force-with-lease origin HEAD:main
