name: Capture Calendar (mobile shot)

on:
  workflow_dispatch:
  schedule:
    - cron: "*/15 * * * *"   # 15분마다

permissions:
  contents: write

jobs:
  capture:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Install deps (puppeteer + fonts)
        run: |
          sudo apt-get update
          sudo apt-get install -y fonts-noto fonts-noto-cjk
          npm i puppeteer@22.15.0

      - name: Run node capture.js
        run: node capture.js

      - name: Commit & push image
        run: |
          git config user.name "${{ github.actor }}"
          git config user.email "${{ github.actor }}@users.noreply.github.com"
          git add docs/calendar_mobile.png
          git commit -m "auto: update mobile calendar shot" || echo "no changes"
          git push
