name: Capture Calendar (mobile shot)

on:
  workflow_dispatch:
  push:
    paths:
      - "capture.js"
      - ".github/workflows/capture.yml"
      - "package.json"
      - "package-lock.json"

jobs:
  capture:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Install deps
        run: npm ci || npm i

      - name: Run capture
        run: node capture.js

      - name: Commit & push image
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git fetch origin main
          git pull --rebase origin main || true
          mkdir -p docs/capture
          git add docs/capture/calendar_mobile.png
          git commit -m "chore: update screenshot $(date -u '+%Y-%m-%dT%H:%M:%SZ')" || echo "no changes"
          git push origin HEAD:main
