name: Capture Calendar (mobile shot)

on:
  workflow_dispatch:

jobs:
  capture:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install puppeteer (local)
        run: |
          npm init -y >/dev/null 2>&1 || true
          npm i puppeteer@22

      - name: Run capture.js
        run: node capture.js

      # ★ 생성 확인(여기서 실제로 파일이 보이면 OK)
      - name: Verify output
        run: |
          echo "PWD=$(pwd)"
          ls -la
          ls -la docs || true
          ls -la docs/capture || true

      - name: Commit & push image (rebase)
        run: |
          git config user.name  "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

          # 변경 사항 확인
          if git diff --quiet --exit-code -- docs/capture/calendar_mobile.png; then
            echo "no changes"; exit 0
          fi

          git fetch origin main
          git pull --rebase origin main

          git add docs/capture/calendar_mobile.png
          git commit -m "chore: update mobile calendar screenshot $(date -u +'%Y-%m-%dT%H:%M:%SZ')"
          git push origin HEAD:main
