name: Capture Calendar (mobile shot)

on:
  workflow_dispatch:

jobs:
  capture:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install Korean fonts
        run: |
          sudo apt-get update
          sudo apt-get install -y fonts-noto-cjk fonts-noto-color-emoji

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Sync with origin/main (clean workspace)
        run: |
          git fetch origin main
          git reset --hard origin/main
          git clean -fd
          rm -rf node_modules package-lock.json

      # 🟢 puppeteer 설치 추가
      - name: Install puppeteer
        run: |
          npm init -y >/dev/null 2>&1 || true
          npm install puppeteer@22

      - name: Run capture.js
        run: node capture.js

      - name: Verify output
        run: |
          ls -al docs/capture || true

      - name: Commit & push image (rebase)
        run: |
          set -e
          mkdir -p docs/capture
          if git diff --quiet --exit-code docs/capture/calendar_mobile.png; then
            echo "no changes"
            exit 0
          fi

          git config user.name  "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

          git add docs/capture/calendar_mobile.png
          git commit -m "chore: update screenshot $(date -u +'%Y-%m-%dT%H:%M:%SZ')"

          git pull --rebase origin main
          git push origin HEAD:main
