name: Capture Calendar (mobile shot)

on:
  workflow_dispatch:

jobs:
  capture:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          persist-credentials: true

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install Korean fonts
        run: |
          sudo apt-get update
          sudo apt-get install -y fonts-noto-cjk fonts-noto-color-emoji

      # 깨끗한 작업공간으로 맞추기
      - name: Sync with origin/main (clean workspace)
        run: |
          git fetch origin main
          git reset --hard origin/main
          git clean -fd
          rm -rf node_modules package-lock.json

      - name: Install puppeteer
        run: |
          npm init -y >/dev/null 2>&1 || true
          npm install puppeteer@22

      - name: Run capture.js
        run: node capture.js

      # 파일이 실제로 생성/수정됐는지 해시로 확인
      - name: Verify output
        run: |
          mkdir -p docs/capture
          test -f docs/capture/calendar_mobile.png || (echo "PNG not found!" && exit 1)
          echo "SHA256:"
          sha256sum docs/capture/calendar_mobile.png
          echo "Git status for the file:"
          git status --porcelain=v1 docs/capture/calendar_mobile.png || true

      # 변경 여부와 관계없이 '해당 파일'을 커밋하게 구성
      - name: Commit & push image (rebase)
        run: |
          set -e
          git config user.name  "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

          git add docs/capture/calendar_mobile.png || true

          # 변경이 없으면 메시지 남기고 넘어가되, 변경이 있으면 커밋
          if git diff --cached --quiet -- docs/capture/calendar_mobile.png; then
            echo "No diff for calendar_mobile.png (content identical) — nothing to commit."
          else
            git commit -m "chore: update mobile calendar screenshot $(date -u +'%Y-%m-%dT%H:%M:%SZ')"
            git pull --rebase origin main
            git push origin HEAD:main
          fi
